---
- name: Ensure config directory
  file:
    state: directory
    path: "{{ bot.config_dir }}/{{ item }}"
    mode: 0755
    owner: root
    group: root
  with_items:
    - data
    - templates

- name: Ensure notification template config
  copy:
    src: alertmanager-bot/default.tmpl
    dest: "{{ bot.config_dir }}/templates/default.tmpl"
    mode: 0644
    owner: root
    group: root
  register: bot_config

- name: Start docker alertmanager-bot container
  community.docker.docker_compose:
    state: present
    project_name: "{{ bot.container_name }}"
    restarted: "{{ 'yes' if bot_config.changed else 'no' }}"
    definition:
      version: '2'
      services:
        alertmanager_bot:
          image: "{{ bot.docker_image }}"
          container_name: "{{ bot.container_name }}"
          volumes:
            - "{{ bot.config_dir }}/data/:/data"
            - "{{ bot.config_dir }}/templates/default.tmpl:/templates/default.tmpl"
          ports:
            - "127.0.0.1:{{ bot.host_port }}:{{ bot.host_port }}"
          hostname: "{{ bot.container_name }}"
          restart: always
          labels: "{{ bot.docker_labels }}"
          environment:
            ALERTMANAGER_URL: http://{{ alertmanager_container_name }}:9093
            BOLT_PATH: /data/bot.db
            STORE: bolt
            TELEGRAM_ADMIN: '{{ bot.telegram_admin }}'
            TELEGRAM_TOKEN: '{{ bot.telegram_token }}'
            TEMPLATE_PATHS: /templates/default.tmpl
            LISTEN_ADDR: '0.0.0.0:{{ bot.host_port }}'
      networks:
        default:
          external:
            name: "{{ alertmanager_docker_network_name }}"
